<?php require __DIR__.'/includes/app.php'; $all=projects(); $featured=array_values(array_filter($all,fn($p)=>!empty($p['featured']))); if(!$featured)$featured=array_slice($all,0,6); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Galindos Builders LLC | Framing & Construction</title><meta name="description" content="Galindos Builders LLC delivers professional framing and construction services with craftsmanship, safety and dependable project execution."><link rel="stylesheet" href="/assets/css/site.css"><script defer src="/assets/js/site.js"></script></head><body>
<header class="site-header"><a class="brand" href="/"><span class="brand-mark">GB</span><span>GALINDOS <b>BUILDERS LLC</b></span></a><button class="menu" aria-label="Open navigation">☰</button><nav><?php foreach(tabs() as $tab): if(empty($tab['visible']))continue; ?><a href="<?=e($tab['url'])?>"><?=e($tab['label'])?></a><?php endforeach; ?><a class="nav-cta" href="#contact">Start a Project</a></nav></header>
<main><section class="hero"><div class="hero-shade"></div><div class="hero-content"><p class="eyebrow">BUILT WITH PURPOSE</p><h1>Craftsmanship that<br><em>frames the future.</em></h1><p>Professional framing and construction built around quality, safety, communication and dependable execution.</p><div class="actions"><a class="btn primary" href="/projects.php">Explore Our Work</a><a class="btn ghost" href="#contact">Request a Quote</a></div></div><div class="hero-stat"><strong>QUALITY</strong><span>From layout to final detail</span></div></section>
<section class="intro" id="about"><div><p class="eyebrow dark">GALINDOS BUILDERS LLC</p><h2>Working together.<br>Building it right.</h2></div><div><p>We bring a hands-on approach to every project, coordinating crews, schedules and details with one goal: deliver strong work our clients can count on.</p><a class="text-link" href="#services">WHAT WE DO →</a></div></section>
<section class="values"><article><span>01</span><h3>Integrity</h3><p>Clear communication and accountability from start to finish.</p></article><article><span>02</span><h3>Craftsmanship</h3><p>Precise work, durable results and attention to the details that matter.</p></article><article><span>03</span><h3>Safety</h3><p>A jobsite culture centered on planning, awareness and responsible execution.</p></article><article><span>04</span><h3>Partnership</h3><p>We work closely with owners, contractors and trades to keep projects moving.</p></article></section>
<section class="services" id="services"><div class="section-heading"><p class="eyebrow">OUR CAPABILITIES</p><h2>Built for demanding projects.</h2></div><div class="service-grid"><article><b>01</b><h3>Wood Framing</h3><p>Structural framing for residential and commercial construction.</p></article><article><b>02</b><h3>Construction</h3><p>Reliable field execution with a focus on schedule, coordination and quality.</p></article><article><b>03</b><h3>Project Support</h3><p>Experienced crews ready to support complex scopes and active jobsites.</p></article></div></section>
<section class="projects-section"><div class="section-heading row"><div><p class="eyebrow dark">SELECTED WORK</p><h2>Featured Projects</h2></div><a class="text-link" href="/projects.php">VIEW ALL PROJECTS →</a></div><?php if($featured): ?><div class="project-grid"><?php foreach(array_slice($featured,0,6) as $p): $img=$p['images'][0]??''; ?><a class="project-card" href="/project.php?job=<?=urlencode($p['slug'])?>"><div class="project-image" style="background-image:url('<?=e($img)?>')"></div><div><small><?=e($p['category']??'PROJECT')?></small><h3><?=e($p['name'])?></h3><p><?=e($p['location']??'')?></p></div></a><?php endforeach; ?></div><?php else: ?><div class="empty-projects"><h3>Your work belongs here.</h3><p>Use the admin dashboard to upload job photos, custom project names and categories.</p></div><?php endif; ?></section>
<section class="contact" id="contact"><p class="eyebrow">LET'S BUILD</p><h2>Have a project in mind?</h2><p>Tell us about the scope, schedule and location. We’ll get back to you to discuss the next steps.</p><a class="btn primary" href="mailto:info@galindosbuildersllc.com">Contact Galindos Builders</a></section></main>
<footer><div class="brand"><span class="brand-mark">GB</span><span>GALINDOS <b>BUILDERS LLC</b></span></div><p>Professional framing & construction.</p><p>© <?=date('Y')?> Galindos Builders LLC. All rights reserved.</p></footer></body></html>