-- Galindos Builders LLC CMS schema
-- MySQL 8+ / MariaDB 10.4+
CREATE DATABASE IF NOT EXISTS galindosbuilders CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE galindosbuilders;

CREATE TABLE IF NOT EXISTS site_settings (
 setting_key VARCHAR(100) PRIMARY KEY,
 setting_value LONGTEXT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admins (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pages (
 id VARCHAR(32) PRIMARY KEY,
 slug VARCHAR(160) NOT NULL UNIQUE,
 title VARCHAR(255) NOT NULL,
 eyebrow VARCHAR(255) NULL,
 hero_text TEXT NULL,
 content LONGTEXT NULL,
 cta_title VARCHAR(255) NULL,
 cta_text TEXT NULL,
 cta_label VARCHAR(120) NULL,
 cta_url VARCHAR(500) NULL,
 seo_title VARCHAR(255) NULL,
 seo_description TEXT NULL,
 sort_order INT NOT NULL DEFAULT 0,
 visible TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS navigation_tabs (
 id VARCHAR(100) PRIMARY KEY,
 label VARCHAR(120) NOT NULL,
 url VARCHAR(500) NULL,
 page_slug VARCHAR(160) NULL,
 visible TINYINT(1) NOT NULL DEFAULT 1,
 sort_order INT NOT NULL DEFAULT 50,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(page_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS services (
 id VARCHAR(100) PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 description TEXT NULL,
 sort_order INT NOT NULL DEFAULT 0,
 visible TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS projects (
 id VARCHAR(32) PRIMARY KEY,
 slug VARCHAR(190) NOT NULL UNIQUE,
 name VARCHAR(255) NOT NULL,
 location VARCHAR(255) NULL,
 category VARCHAR(120) NULL,
 status VARCHAR(100) NULL,
 description LONGTEXT NULL,
 featured TINYINT(1) NOT NULL DEFAULT 0,
 sort_order INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project_images (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id VARCHAR(32) NOT NULL,
 image_url VARCHAR(700) NOT NULL,
 alt_text VARCHAR(255) NULL,
 sort_order INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_project_images_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
 INDEX(project_id,sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS seo_settings (
 page_key VARCHAR(160) PRIMARY KEY,
 title VARCHAR(255) NULL,
 description TEXT NULL,
 keywords TEXT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quote_submissions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 email VARCHAR(255) NULL,
 phone VARCHAR(80) NULL,
 project_type VARCHAR(160) NULL,
 location VARCHAR(255) NULL,
 message LONGTEXT NULL,
 status VARCHAR(40) NOT NULL DEFAULT 'new',
 submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(status,submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Compatibility/migration store for older installs. New configurable data uses normalized tables above.
CREATE TABLE IF NOT EXISTS site_store (
 store_key VARCHAR(100) PRIMARY KEY,
 payload LONGTEXT NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
