-- Additive tables only. Existing content is never truncated or dropped.
CREATE TABLE IF NOT EXISTS sessions (
 sid VARCHAR(128) PRIMARY KEY, data MEDIUMTEXT NOT NULL, expires_at DATETIME NOT NULL, INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS request_limits (
 limit_key CHAR(64) PRIMARY KEY, hits INT NOT NULL DEFAULT 0, reset_at DATETIME NOT NULL, INDEX(reset_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS media (
 id VARCHAR(32) PRIMARY KEY, url VARCHAR(700) NOT NULL, title VARCHAR(255) NOT NULL DEFAULT '',
 alt_text VARCHAR(255) NOT NULL DEFAULT '', folder VARCHAR(100) NOT NULL DEFAULT '', mime_type VARCHAR(100) NOT NULL,
 size_bytes BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS homepage_sections (
 section_key VARCHAR(40) PRIMARY KEY, enabled TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS service_areas (
 id VARCHAR(32) PRIMARY KEY, slug VARCHAR(160) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, location VARCHAR(255) NULL,
 hero_text TEXT NULL, content LONGTEXT NULL, featured_image VARCHAR(700) NULL, seo_title VARCHAR(255) NULL,
 seo_description TEXT NULL, canonical_url VARCHAR(700) NULL, og_image VARCHAR(700) NULL,
 robots VARCHAR(40) NOT NULL DEFAULT 'index,follow', visible TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS lead_notes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, lead_id BIGINT UNSIGNED NOT NULL, author_id BIGINT UNSIGNED NOT NULL,
 note TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(lead_id) REFERENCES quote_submissions(id) ON DELETE CASCADE, FOREIGN KEY(author_id) REFERENCES admins(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS mail_outbox (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, recipient VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL,
 body TEXT NOT NULL, attempts INT NOT NULL DEFAULT 0, available_at DATETIME NOT NULL, locked_until DATETIME NULL,
 sent_at DATETIME NULL, last_error VARCHAR(500) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(sent_at,available_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
