<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?=e($title)?> | Galindos Builders</title><link rel="stylesheet" href="/admin/admin.css"><script defer src="/assets/js/admin.js"></script></head><body>
<aside><div class="admin-logo">GB</div><h2>Galindos Builders</h2><a href="/admin">Dashboard</a>
<?php foreach($resources as $navkey=>$r):if(can($user,$r['permission'])):?><a href="/admin/<?=e($navkey)?>"><?=e($r['label'])?></a><?php endif;endforeach;?>
<?php foreach(['media'=>['content','Media Library'],'home'=>['content','Homepage Content'],'sections'=>['content','Homepage Sections'],'leads'=>['leads','Quote Requests'],'mail'=>['leads','Email Delivery'],'settings'=>['settings','Settings & Branding'],'users'=>['users','Administrator Accounts']] as $navkey=>[$permission,$label]):if(can($user,$permission)):?><a href="/admin/<?=e($navkey)?>"><?=e($label)?></a><?php endif;endforeach;?>
<a href="/" target="_blank" rel="noopener">View Website ↗</a><form action="/admin/logout" method="post"><?php csrf_input();?><button>Sign Out</button></form></aside>
<main class="admin-main"><header><div><small>WEBSITE ADMIN</small><h1><?=e($title)?></h1></div><span><?=e($user['username'])?> · <?=e($user['role'])?></span></header>
<?php if($mode==='dashboard'):?><section class="stats"><?php foreach($stats as [$label,$number]):?><article><strong><?=e($number)?></strong><span><?=e($label)?></span></article><?php endforeach;?></section><section class="panel"><h2>Manage your website</h2><p>Publish case studies, manage reusable photos, arrange your homepage and follow up with customers using the menu.</p></section><?php endif;?>
<?php if($mode==='list'):?><section class="panel"><a href="/admin/<?=e($key)?>/new">Add <?=e($resource['label'])?> →</a><div class="table-wrap"><table><thead><tr><th>Name</th><th>Slug / URL</th><th>Published</th><th>Actions</th></tr></thead><tbody><?php foreach($items as $row):$rid=$row[$resource['id']??'id'];?><tr><td><?=e($row['name']??$row['title']??$row['label']??$row['page_key'])?></td><td><?=e($row['slug']??$row['url']??$row['page_key']??'')?></td><td><?=empty($row['visible'])&&isset($row['visible'])?'Hidden':'Yes'?></td><td><a href="/admin/<?=e($key)?>/<?=e(rawurlencode((string)$rid))?>">Edit</a><form class="compact" method="post" action="/admin/<?=e($key)?>/<?=e(rawurlencode((string)$rid))?>/delete" data-confirm="Delete this record?"><?php csrf_input();?><button class="danger">Delete</button></form></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<?php if(in_array($mode,['edit','settings'],true)):?><datalist id="library-urls"><?php foreach($media as $m):?><option value="<?=e($m['url'])?>"><?=e($m['title'])?></option><?php endforeach;?></datalist><section class="panel"><form class="form-grid" method="post" action="/admin/<?=e($key)?><?=$mode==='edit'?'/save':''?>"><?php csrf_input();if($mode==='edit'):?><input type="hidden" name="record_id" value="<?=e($record[$resource['id']??'id']??'')?>"><?php endif;render_fields($fields,$record,$services??[]);?><button>Save Changes</button></form><p>Image URL fields offer images from the media library.</p></section>
<?php if($key==='settings'):?><section class="panel"><h2>Upload Branding Images</h2><p>Uploads apply immediately and are added to the reusable media library.</p><?php foreach(['header_logo_url'=>'Header logo','favicon_url'=>'Favicon','meta_image_url'=>'Social media image'] as $setting=>$label):?><form class="form-grid" action="/admin/settings/images/<?=e($setting)?>" method="post" enctype="multipart/form-data" data-upload data-branding-upload><?php csrf_input();?><label class="full"><?=e($label)?> upload (up to 10 MB)<input type="file" name="image" accept="image/png,image/jpeg,image/webp,image/gif<?=$setting==='favicon_url'?',image/x-icon,image/vnd.microsoft.icon':''?>" required></label><div class="branding-preview full" data-branding-preview><span>Current <?=e($label)?></span><img class="<?=$setting==='favicon_url'?'favicon-preview':'meta-preview'?>" alt="Current <?=e($label)?>" <?php if(image_url($record[$setting]??'')):?>src="<?=e(image_url($record[$setting]))?>"<?php else:?>hidden<?php endif;?>></div><button>Upload &amp; Apply <?=e($label)?></button><p role="status" data-upload-status></p></form><?php endforeach;?></section><?php endif;endif;?>
<?php if($mode==='edit'&&$key==='projects'&&!empty($record['id'])):?><section class="panel"><h2>Gallery</h2><form class="form-grid" method="post" action="/admin/projects/<?=e($record['id'])?>/gallery"><?php csrf_input();?><label>Library image<select name="media_id" required><?php foreach($media as $m):?><option value="<?=e($m['id'])?>"><?=e($m['title']?:$m['url'])?></option><?php endforeach;?></select></label><?php render_fields(gallery_fields(),['sort_order'=>count($gallery)*10]);?><button>Add to Gallery</button></form><div class="image-manager"><?php foreach($gallery as $image):?><article><img src="<?=e(image_url($image['image_url']))?>" alt="<?=e($image['alt_text'])?>"><form class="image-form" method="post" action="/admin/projects/<?=e($record['id'])?>/gallery/<?=e($image['id'])?>"><?php csrf_input();render_fields(gallery_fields(),$image);?><button name="action" value="save">Save</button><button class="danger" name="action" value="remove">Remove from Gallery</button></form></article><?php endforeach;?></div></section><?php endif;?>
<?php if($mode==='sections'):?><section class="panel"><p>Lower order numbers appear first. Uncheck a section to hide it.</p><?php foreach($items as $s):?><form class="section-row" method="post" action="/admin/sections/<?=e($s['section_key'])?>"><?php csrf_input();?><strong><?=e($s['section_key'])?></strong><label class="check"><input type="checkbox" name="enabled" value="1" <?=$s['enabled']?'checked':''?>>Enabled</label><label>Order<input type="number" name="sort_order" value="<?=e($s['sort_order'])?>"></label><button>Save</button></form><?php endforeach;?></section><?php endif;?>
<?php if($mode==='media'):?><section class="panel"><h2>Upload an Image</h2><form class="form-grid" action="/admin/media/upload" method="post" enctype="multipart/form-data" data-upload><?php csrf_input();?><label>Image (up to 10 MB)<input type="file" name="image" accept="image/png,image/jpeg,image/webp,image/gif,image/x-icon" required></label><?php render_fields(['title'=>['label'=>'Title'],'alt_text'=>['label'=>'Alt text'],'folder'=>['label'=>'Folder / Category']],[]);?><button>Upload</button><p role="status" data-upload-status></p></form></section><section class="panel"><label>Search library<input data-media-filter></label><div class="image-manager"><?php foreach($items as $m):?><article data-media-search="<?=e(strtolower($m['title'].' '.$m['folder']))?>"><img src="<?=e(image_url($m['url']))?>" alt="<?=e($m['alt_text'])?>" loading="lazy"><form class="image-form" method="post" action="/admin/media/<?=e($m['id'])?>/save"><?php csrf_input();render_fields(['title'=>['label'=>'Title'],'alt_text'=>['label'=>'Alt text'],'folder'=>['label'=>'Folder']],$m);?><label>Reusable URL<input value="<?=e($m['url'])?>" readonly></label><button>Save</button></form><?php if(str_starts_with($m['url'],'/uploads/media/')):?><form class="image-form" method="post" action="/admin/media/<?=e($m['id'])?>/replace" enctype="multipart/form-data" data-upload><?php csrf_input();?><label>Replace image (same format)<input type="file" name="image" required></label><button>Replace Everywhere</button><p role="status" data-upload-status></p></form><?php endif;?><form class="image-form" method="post" action="/admin/media/<?=e($m['id'])?>/delete" data-confirm="Delete this library image? In-use images cannot be deleted."><?php csrf_input();?><button class="danger">Delete</button></form></article><?php endforeach;?></div></section><?php endif;?>
<?php if($mode==='leads'):?><section class="panel"><form method="get"><label>Status<select name="status"><option value="">All</option><?php foreach($leadStatuses as $s):?><option <?=$status===$s?'selected':''?>><?=e($s)?></option><?php endforeach;?></select></label><button>Filter</button></form><p>Showing the latest 500 matching requests.</p><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Project</th><th>Status</th><th>Assigned to</th><th>Submitted</th></tr></thead><tbody><?php foreach($items as $r):?><tr><td><a href="/admin/leads/<?=e($r['id'])?>"><?=e($r['name'])?></a><br><?=e($r['email'])?></td><td><?=e($r['project_type'])?><br><?=e($r['location'])?></td><td><?=e($r['status'])?></td><td><?=e($r['assignee']?:'Unassigned')?></td><td><?=e($r['submitted_at'])?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<?php if($mode==='lead'):?><section class="panel"><h2><?=e($record['name'])?></h2><p><?=e($record['email'])?> · <?=e($record['phone'])?></p><p><?=e($record['project_type'])?> · <?=e($record['location'])?></p><p class="preserve-lines"><?=e($record['message'])?></p><form class="form-grid" method="post"><?php csrf_input();?><label>Status<select name="status"><?php foreach($leadStatuses as $s):?><option <?=strcasecmp($s,$record['status'])===0?'selected':''?>><?=e($s)?></option><?php endforeach;?></select></label><label>Assigned to<select name="assigned_to"><option value="">Unassigned</option><?php foreach($users as $a):?><option value="<?=e($a['id'])?>" <?=(string)$a['id']===(string)$record['assigned_to']?'selected':''?>><?=e($a['username'])?></option><?php endforeach;?></select></label><label class="full">Add internal note<textarea name="note" maxlength="10000"></textarea></label><button>Save Request</button></form></section><section class="panel"><h2>Internal Notes</h2><?php foreach($notes as $n):?><article><p class="preserve-lines"><?=e($n['note'])?></p><small><?=e($n['username'])?> · <?=e($n['created_at'])?></small><hr></article><?php endforeach;?></section><?php endif;?>
<?php if($mode==='users'):?><section class="panel"><h2>Add Account</h2><p>Owners manage everything. Editors manage content and media. Sales accounts manage leads and email delivery.</p><form class="form-grid" method="post"><?php csrf_input();?><label>Username<input name="username" required minlength="3" maxlength="100"></label><label>Email<input name="email" type="email" maxlength="255"></label><label>Password<input name="password" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label><?php role_select('editor');?><button>Create Account</button></form></section><section class="panel"><?php foreach($items as $a):?><h3><?=e($a['username'])?></h3><form class="form-grid" method="post" action="/admin/users/<?=e($a['id'])?>"><?php csrf_input();role_select($a['role']);?><label class="check"><input type="checkbox" name="active" value="1" <?=$a['active']?'checked':''?>>Active</label><label>Reset password (leave blank to keep)<input name="password" type="password" minlength="12" maxlength="128" autocomplete="new-password"></label><button>Save Account</button></form><hr><?php endforeach;?></section><?php endif;?>
<?php if($mode==='mail'):?><section class="panel"><p>Configure SMTP and the cPanel cron job to deliver queued notifications.</p><div class="table-wrap"><table><thead><tr><th>Recipient</th><th>Subject</th><th>Attempts</th><th>Delivery</th><th>Action</th></tr></thead><tbody><?php foreach($items as $m):?><tr><td><?=e($m['recipient'])?></td><td><?=e($m['subject'])?></td><td><?=e($m['attempts'])?></td><td><?=e($m['sent_at']?:$m['last_error']?:'Pending')?></td><td><?php if(!$m['sent_at']):?><form method="post" action="/admin/mail/<?=e($m['id'])?>/retry"><?php csrf_input();?><button>Retry</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
</main></body></html>
<?php
function render_fields(array $fields,array $record,array $services=[]):void {
    foreach($fields as $key=>$f){$type=$f['type']??'text';$v=$record[$key]??($type==='select'?$f['options'][0]:'');$label=$f['label']??ucwords(str_replace('_',' ',$key));
        echo '<label class="'.(in_array($type,['textarea','html'],true)?'full':($type==='checkbox'?'check':'')).'">'.e($label);
        if($type==='checkbox')echo '<input type="checkbox" name="'.e($key).'" value="1" '.($v?'checked':'').'>';
        elseif(in_array($type,['textarea','html'],true))echo '<textarea name="'.e($key).'" rows="'.($type==='html'?12:4).'" maxlength="'.e($f['max']??10000).'">'.e($v).'</textarea>';
        elseif(in_array($type,['select','service'],true)){$options=$type==='service'?array_column($services,'name','id'):array_combine($f['options'],$f['options']);echo '<select name="'.e($key).'">';if($type==='service')echo '<option value="">None</option>';foreach($options as $option=>$text)echo '<option value="'.e($option).'" '.((string)$v===(string)$option?'selected':'').'>'.e($text).'</option>';echo '</select>';}
        else echo '<input name="'.e($key).'" value="'.e($v).'" type="'.(in_array($type,['number','date','email'],true)?$type:'text').'" '.(!empty($f['required'])?'required':'').' maxlength="'.e($f['max']??255).'" '.($type==='url'?'list="library-urls"':'').'>';
        echo '</label>';
    }
}
function role_select(string $value):void {render_fields(['role'=>['label'=>'Role','type'=>'select','options'=>['owner','editor','sales']]],['role'=>$value]);}
